project:
  type: website

website:
  title: "BioForge"
  search: false
  navbar:
    logo: assets/images/logo.png
    left:
      - href: people.qmd
        text: "{{< fa people-group >}} People"
      - href: research.qmd
        text: "{{< fa rocket >}} Research"
      - href: resources.qmd
        text: "{{< fa lightbulb >}} Resources"
      - href: values.qmd
        text: "{{< fa hand-holding-heart >}} Values"
    right:
      - href: join.qmd
        text: Join Us
      - href: https://github.com/BecksLab
        icon: github
  page-footer:     
    left:  
      - icon: location-dot
        text: "{{< fa location-dot >}} University of Sheffield, UK"
        href: https://www.sheffield.ac.uk
    right: 
      - icon: code
        text: "{{< fa code >}} Source code"
        href: https://github.com/TanyaS08/TanyaDoesScience

format:
  html:
    theme: [minty, mystyles.scss]
    toc: true
    page-layout: full
    format:
    css: assets/css/styles.css



