project:
  type: website

website:
  title: "the CESSpit"
  search: false
  navbar:
    left:
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research
    right:
      - href: join.qmd
        text: Join Us
      - href: https://github.com/BecksLab
        icon: github

format:
  html:
    theme: cosmo
    toc: true
    format:
    css: assets/css/styles.css



