project:
  type: website

website:
  title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: people.qmd
        text: People

format:
  html:
    theme: cosmo
    toc: true
    format:
    css: assets/css/styles.css



