project:
  type: website

website:
  title: "Beckerman Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research
    right: 
      - icon: github
        href: https://github.com/BecksLab

format:
  html:
    theme: cosmo
    toc: true
    format:
    css: assets/css/styles.css



