project:
  type: website

website:
  title: "BioForge"
  search: false
  navbar:
    left:
      - href: people.qmd
        text: "{{< fa people-group >}} People"
      - href: research.qmd
        text: "{{< fa rocket >}} Research"
      - href: resources.qmd
        text: "{{< fa lightbulb >}} Resources"
      - href: values.qmd
        text: "{{< fa hand-holding-heart >}} Values"
    right:
      - href: join.qmd
        text: Join Us
      - href: https://github.com/BecksLab
        icon: github

format:
  html:
    theme: [cosmo, mystyles.scss]
    toc: true
    page-layout: full
    format:
    css: assets/css/styles.css



