---
title: "Values"
toc: false
---

[Welcome to the BioForge Research Group!]{.research-question}

We encourage all individuals and organizations who are interested in developing and promoting best practice in the assessment of researchers and scholarly research to sign [Declaration on Research Assessment (DORA)](https://sfdora.org).

In this lab, we study a variety of habitats, taxa and processes, with the core elements of using data, math and computational techniques to gain better understanding of ecological systems.

We are committed to applying what we learn to making the world a better place — by supporting sustainability and productivity in working ecosystems, by making the work we do accessible to the broader community, and by drawing in diverse viewpoints to enhance mutual understanding of science, scientists, and the needs of the world.

We believe that “science” is one way of learning about the world, alongside art, imagination, intuition, faith, vibes, …. We know there is value in pretending that the world can be simplified to mathematics or code, but we know these constructs are not truths.

We believe that curiosity-driven research can lead to actionable science, if it is used to generate questions, not give answers.

We believe that algorithms cannot be trusted to make decisions on behalf of people. We subscribe to the principles outlined in the Montréal Declaration for a Responsible Development of Artifical Intelligence.

## Our commitments to open science

First and foremost, we are an open science lab. There are several major facets to this, but the core is: the way this lab operates is inspired by the time that Tanya spent at the [Poisot lab](https://poisotlab.io/values/) and resets on the belief that participation in science is a public act, and done for public good. As such it is essential that we give back what we take from the community, while striving to cultivate a research space that is healthy, collaborative, and a truly inclusive.

This is our commitment, as open scientists:

-   Do no harm.

-   Make supporting research data freely available whenever possible, to support future use in meta-analyses, reviews.

-   Respect sensitive information and maintain the privacy and confidentiality in cases where data or research products require it. 

-   Produce and share reproducible, re-usable code, so people can understand our assumptions and workflows, and so that future scientists can learn from our efforts without needing to duplicate them.

-   Publish final manuscripts AND intermediate research products in the most accessible formats available to us.

-   Seek out the expertise of stakeholders outside our immediate research environment. Invite comment and participation. Welcome feedback.

-   Acknowledge contributions to our work, and cite the ideas of others.

-   Act as ambassadors of open science, to the broader scientific community and the world.

## Code of conduct

### Flexible working hours

The assumption is that every member is already self-motivated and may choose to deviate from a traditional 9 to 5 to best suit their needs. They are welcome to send work-related messages, or submit pull requests outside of traditional working hours or days, with the expectation that other members are *not* required to respond to them outside of their typical working hours.

Members are welcome to work flexibly or remotely for any reason, however it is encouraged that they attend our weekly group meeting and to participate in activities.
