on:
  workflow_dispatch:
  pull_request:

name: Quarto Render test

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
          tinytex: true


      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2       
        with:
          to: html